/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Actor {
    #[serde(rename = "actor_id")] pub actor_id: i32,
    #[serde(rename = "first_name")] pub first_name: String,
    #[serde(rename = "last_name")] pub last_name: String,
    #[serde(rename = "last_update")] pub last_update: String,
}
