/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_actor(client: &Client, entity: &Actor) -> Result<Actor, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<Actor>()
        .values(&[&entity.actor_id, &entity.first_name, &entity.last_name, &entity.last_update])
        .returning(&["actor_id", "first_name", "last_name", "last_update"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Actor {
        actor_id: row.get("actor_id"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        last_update: row.get("last_update"),
    })
}

pub async fn get_actor(client: &Client, id: i32) -> Result<Actor, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<Actor>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Actor {
        actor_id: row.get("actor_id"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        last_update: row.get("last_update"),
    })
}

pub async fn update_actor(client: &Client, entity: &Actor) -> Result<Actor, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<Actor>()
        .set_values(&[("actor_id", &entity.actor_id), ("first_name", &entity.first_name), ("last_name", &entity.last_name), ("last_update", &entity.last_update)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Actor {
        actor_id: row.get("actor_id"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        last_update: row.get("last_update"),
    })
}

pub async fn delete_actor(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<Actor>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_actor(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<Actor>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<Actor>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| Actor {
        actor_id: row.get("actor_id"),
        first_name: row.get("first_name"),
        last_name: row.get("last_name"),
        last_update: row.get("last_update"),
    }).collect();
    
    Ok(entities)
}
