/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Address {
    #[serde(rename = "address")] pub address: String,
    #[serde(rename = "address2")] pub address2: String,
    #[serde(rename = "address_id")] pub address_id: i32,
    #[serde(rename = "city_id")] pub city_id: i16,
    #[serde(rename = "district")] pub district: String,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "phone")] pub phone: String,
    #[serde(rename = "postal_code")] pub postal_code: String,
}
