/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_category(client: &Client, entity: &Category) -> Result<Category, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<Category>()
        .values(&[&entity.category_id, &entity.last_update, &entity.name])
        .returning(&["category_id", "last_update", "name"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Category {
        category_id: row.get("category_id"),
        last_update: row.get("last_update"),
        name: row.get("name"),
    })
}

pub async fn get_category(client: &Client, id: i32) -> Result<Category, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<Category>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Category {
        category_id: row.get("category_id"),
        last_update: row.get("last_update"),
        name: row.get("name"),
    })
}

pub async fn update_category(client: &Client, entity: &Category) -> Result<Category, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<Category>()
        .set_values(&[("category_id", &entity.category_id), ("last_update", &entity.last_update), ("name", &entity.name)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Category {
        category_id: row.get("category_id"),
        last_update: row.get("last_update"),
        name: row.get("name"),
    })
}

pub async fn delete_category(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<Category>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_category(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<Category>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<Category>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| Category {
        category_id: row.get("category_id"),
        last_update: row.get("last_update"),
        name: row.get("name"),
    }).collect();
    
    Ok(entities)
}
