/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Customer {
    #[serde(rename = "active")] pub active: i32,
    #[serde(rename = "activebool")] pub activebool: bool,
    #[serde(rename = "address_id")] pub address_id: i16,
    #[serde(rename = "create_date")] pub create_date: chrono::NaiveDate,
    #[serde(rename = "customer_id")] pub customer_id: i32,
    #[serde(rename = "email")] pub email: String,
    #[serde(rename = "first_name")] pub first_name: String,
    #[serde(rename = "last_name")] pub last_name: String,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "store_id")] pub store_id: i16,
}
