/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_film_category(client: &Client, entity: &FilmCategory) -> Result<FilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<FilmCategory>()
        .values(&[&entity.category_id, &entity.film_id, &entity.last_update])
        .returning(&["category_id", "film_id", "last_update"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(FilmCategory {
        category_id: row.get("category_id"),
        film_id: row.get("film_id"),
        last_update: row.get("last_update"),
    })
}

pub async fn get_film_category(client: &Client, id: i32) -> Result<FilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<FilmCategory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(FilmCategory {
        category_id: row.get("category_id"),
        film_id: row.get("film_id"),
        last_update: row.get("last_update"),
    })
}

pub async fn update_film_category(client: &Client, entity: &FilmCategory) -> Result<FilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<FilmCategory>()
        .set_values(&[("category_id", &entity.category_id), ("film_id", &entity.film_id), ("last_update", &entity.last_update)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(FilmCategory {
        category_id: row.get("category_id"),
        film_id: row.get("film_id"),
        last_update: row.get("last_update"),
    })
}

pub async fn delete_film_category(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<FilmCategory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_film_category(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<FilmCategory>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<FilmCategory>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| FilmCategory {
        category_id: row.get("category_id"),
        film_id: row.get("film_id"),
        last_update: row.get("last_update"),
    }).collect();
    
    Ok(entities)
}
