/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Film {
    #[serde(rename = "description")] pub description: String,
    #[serde(rename = "film_id")] pub film_id: i32,
    #[serde(rename = "fulltext")] pub fulltext: String,
    #[serde(rename = "language_id")] pub language_id: i16,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "length")] pub length: i16,
    #[serde(rename = "rating")] pub rating: String,
    #[serde(rename = "release_year")] pub release_year: i32,
    #[serde(rename = "rental_duration")] pub rental_duration: i16,
    #[serde(rename = "rental_rate")] pub rental_rate: bigdecimal::BigDecimal,
    #[serde(rename = "replacement_cost")] pub replacement_cost: bigdecimal::BigDecimal,
    #[serde(rename = "special_features")] pub special_features: String,
    #[serde(rename = "title")] pub title: String,
}
