/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_inventory(client: &Client, entity: &Inventory) -> Result<Inventory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<Inventory>()
        .values(&[&entity.film_id, &entity.inventory_id, &entity.last_update, &entity.store_id])
        .returning(&["film_id", "inventory_id", "last_update", "store_id"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Inventory {
        film_id: row.get("film_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        store_id: row.get("store_id"),
    })
}

pub async fn get_inventory(client: &Client, id: i32) -> Result<Inventory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<Inventory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Inventory {
        film_id: row.get("film_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        store_id: row.get("store_id"),
    })
}

pub async fn update_inventory(client: &Client, entity: &Inventory) -> Result<Inventory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<Inventory>()
        .set_values(&[("film_id", &entity.film_id), ("inventory_id", &entity.inventory_id), ("last_update", &entity.last_update), ("store_id", &entity.store_id)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Inventory {
        film_id: row.get("film_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        store_id: row.get("store_id"),
    })
}

pub async fn delete_inventory(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<Inventory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_inventory(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<Inventory>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<Inventory>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| Inventory {
        film_id: row.get("film_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        store_id: row.get("store_id"),
    }).collect();
    
    Ok(entities)
}
