/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Inventory {
    #[serde(rename = "film_id")] pub film_id: i16,
    #[serde(rename = "inventory_id")] pub inventory_id: i32,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "store_id")] pub store_id: i16,
}
