/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct NicerButSlowerFilmList {
    #[serde(rename = "actors")] pub actors: String,
    #[serde(rename = "category")] pub category: String,
    #[serde(rename = "description")] pub description: String,
    #[serde(rename = "fid")] pub fid: i32,
    #[serde(rename = "length")] pub length: i16,
    #[serde(rename = "price")] pub price: bigdecimal::BigDecimal,
    #[serde(rename = "rating")] pub rating: String,
    #[serde(rename = "title")] pub title: String,
}
