/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Payment {
    #[serde(rename = "amount")] pub amount: bigdecimal::BigDecimal,
    #[serde(rename = "customer_id")] pub customer_id: i16,
    #[serde(rename = "payment_date")] pub payment_date: String,
    #[serde(rename = "payment_id")] pub payment_id: i32,
    #[serde(rename = "rental_id")] pub rental_id: i32,
    #[serde(rename = "staff_id")] pub staff_id: i16,
}
