/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_rental(client: &Client, entity: &Rental) -> Result<Rental, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<Rental>()
        .values(&[&entity.customer_id, &entity.inventory_id, &entity.last_update, &entity.rental_date, &entity.rental_id, &entity.return_date, &entity.staff_id])
        .returning(&["customer_id", "inventory_id", "last_update", "rental_date", "rental_id", "return_date", "staff_id"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Rental {
        customer_id: row.get("customer_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        rental_date: row.get("rental_date"),
        rental_id: row.get("rental_id"),
        return_date: row.get("return_date"),
        staff_id: row.get("staff_id"),
    })
}

pub async fn get_rental(client: &Client, id: i32) -> Result<Rental, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<Rental>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Rental {
        customer_id: row.get("customer_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        rental_date: row.get("rental_date"),
        rental_id: row.get("rental_id"),
        return_date: row.get("return_date"),
        staff_id: row.get("staff_id"),
    })
}

pub async fn update_rental(client: &Client, entity: &Rental) -> Result<Rental, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<Rental>()
        .set_values(&[("customer_id", &entity.customer_id), ("inventory_id", &entity.inventory_id), ("last_update", &entity.last_update), ("rental_date", &entity.rental_date), ("rental_id", &entity.rental_id), ("return_date", &entity.return_date), ("staff_id", &entity.staff_id)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(Rental {
        customer_id: row.get("customer_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        rental_date: row.get("rental_date"),
        rental_id: row.get("rental_id"),
        return_date: row.get("return_date"),
        staff_id: row.get("staff_id"),
    })
}

pub async fn delete_rental(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<Rental>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_rental(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<Rental>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<Rental>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| Rental {
        customer_id: row.get("customer_id"),
        inventory_id: row.get("inventory_id"),
        last_update: row.get("last_update"),
        rental_date: row.get("rental_date"),
        rental_id: row.get("rental_id"),
        return_date: row.get("return_date"),
        staff_id: row.get("staff_id"),
    }).collect();
    
    Ok(entities)
}
