/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Rental {
    #[serde(rename = "customer_id")] pub customer_id: i16,
    #[serde(rename = "inventory_id")] pub inventory_id: i32,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "rental_date")] pub rental_date: String,
    #[serde(rename = "rental_id")] pub rental_id: i32,
    #[serde(rename = "return_date")] pub return_date: String,
    #[serde(rename = "staff_id")] pub staff_id: i16,
}
