/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_sales_by_film_category(client: &Client, entity: &SalesByFilmCategory) -> Result<SalesByFilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<SalesByFilmCategory>()
        .values(&[&entity.category, &entity.total_sales])
        .returning(&["category", "total_sales"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(SalesByFilmCategory {
        category: row.get("category"),
        total_sales: row.get("total_sales"),
    })
}

pub async fn get_sales_by_film_category(client: &Client, id: i32) -> Result<SalesByFilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<SalesByFilmCategory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(SalesByFilmCategory {
        category: row.get("category"),
        total_sales: row.get("total_sales"),
    })
}

pub async fn update_sales_by_film_category(client: &Client, entity: &SalesByFilmCategory) -> Result<SalesByFilmCategory, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<SalesByFilmCategory>()
        .set_values(&[("category", &entity.category), ("total_sales", &entity.total_sales)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(SalesByFilmCategory {
        category: row.get("category"),
        total_sales: row.get("total_sales"),
    })
}

pub async fn delete_sales_by_film_category(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<SalesByFilmCategory>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_sales_by_film_category(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<SalesByFilmCategory>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<SalesByFilmCategory>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| SalesByFilmCategory {
        category: row.get("category"),
        total_sales: row.get("total_sales"),
    }).collect();
    
    Ok(entities)
}
