/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct SalesByStore {
    #[serde(rename = "manager")] pub manager: String,
    #[serde(rename = "store")] pub store: String,
    #[serde(rename = "total_sales")] pub total_sales: bigdecimal::BigDecimal,
}
