/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

use tokio_postgres::Client;
use crate::query_builder::QueryBuilder;

pub async fn create_staff_list(client: &Client, entity: &StaffList) -> Result<StaffList, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::insert::<StaffList>()
        .values(&[&entity.address, &entity.city, &entity.country, &entity.id, &entity.name, &entity.phone, &entity.sid, &entity.zip_code])
        .returning(&["address", "city", "country", "id", "name", "phone", "sid", "zip code"])
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(StaffList {
        address: row.get("address"),
        city: row.get("city"),
        country: row.get("country"),
        id: row.get("id"),
        name: row.get("name"),
        phone: row.get("phone"),
        sid: row.get("sid"),
        zip_code: row.get("zip code"),
    })
}

pub async fn get_staff_list(client: &Client, id: i32) -> Result<StaffList, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::select::<StaffList>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(StaffList {
        address: row.get("address"),
        city: row.get("city"),
        country: row.get("country"),
        id: row.get("id"),
        name: row.get("name"),
        phone: row.get("phone"),
        sid: row.get("sid"),
        zip_code: row.get("zip code"),
    })
}

pub async fn update_staff_list(client: &Client, entity: &StaffList) -> Result<StaffList, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::update::<StaffList>()
        .set_values(&[("address", &entity.address), ("city", &entity.city), ("country", &entity.country), ("id", &entity.id), ("name", &entity.name), ("phone", &entity.phone), ("sid", &entity.sid), ("zip code", &entity.zip_code)])
        .where_clause("id = $1")
        .bind_param(entity.id)
        .build();
    
    let row = client.query_one(&query, &params[..]).await?;
    
    Ok(StaffList {
        address: row.get("address"),
        city: row.get("city"),
        country: row.get("country"),
        id: row.get("id"),
        name: row.get("name"),
        phone: row.get("phone"),
        sid: row.get("sid"),
        zip_code: row.get("zip code"),
    })
}

pub async fn delete_staff_list(client: &Client, id: i32) -> Result<bool, tokio_postgres::Error> {
    let (query, params) = QueryBuilder::delete::<StaffList>()
        .where_clause("id = $1")
        .bind_param(id)
        .build();
    
    let result = client.execute(&query, &params[..]).await?;
    
    Ok(result > 0)
}

pub async fn list_staff_list(client: &Client, limit: Option<i64>, offset: Option<i64>) -> Result<Vec<StaffList>, tokio_postgres::Error> {
    let mut query_builder = QueryBuilder::select::<StaffList>();
    
    if let Some(limit_val) = limit {
        query_builder = query_builder.limit(limit_val as usize);
    }
    
    if let Some(offset_val) = offset {
        query_builder = query_builder.offset(offset_val as usize);
    }
    
    let (query, params) = query_builder.build();
    
    let rows = client.query(&query, &params[..]).await?;
    
    let entities = rows.into_iter().map(|row| StaffList {
        address: row.get("address"),
        city: row.get("city"),
        country: row.get("country"),
        id: row.get("id"),
        name: row.get("name"),
        phone: row.get("phone"),
        sid: row.get("sid"),
        zip_code: row.get("zip code"),
    }).collect();
    
    Ok(entities)
}
