/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Staff {
    #[serde(rename = "active")] pub active: bool,
    #[serde(rename = "address_id")] pub address_id: i16,
    #[serde(rename = "email")] pub email: String,
    #[serde(rename = "first_name")] pub first_name: String,
    #[serde(rename = "last_name")] pub last_name: String,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "password")] pub password: String,
    #[serde(rename = "picture")] pub picture: Vec<u8>,
    #[serde(rename = "staff_id")] pub staff_id: i32,
    #[serde(rename = "store_id")] pub store_id: i16,
    #[serde(rename = "username")] pub username: String,
}
