/*
 * This code was generated by rust_orm_gen.
 * GitHub: https://github.com/tomblanchard312/rust_orm_gen
 * Date: 2024-07-26
 * Author: Tom Blanchard
 */

#[derive(Debug, Serialize, Deserialize)]
pub struct Store {
    #[serde(rename = "address_id")] pub address_id: i16,
    #[serde(rename = "last_update")] pub last_update: String,
    #[serde(rename = "manager_staff_id")] pub manager_staff_id: i16,
    #[serde(rename = "store_id")] pub store_id: i32,
}
